# tasks.yaml

# --- Morning boot rituals ---
- name: Sovereignty sweep
  team: Sovereignty
  args: ["--check-policies", "--report"]
  at: "2025-08-27 08:30"

- name: Diagnostics warmup
  team: Diagnostics
  args: ["--scan", "--quiet"]
  at: "2025-08-27 08:35"

- name: Emotional weather ping
  team: EmotionalWeather
  args: ["--pulse"]
  at: "2025-08-27 08:40"

# --- Frequent background loops ---
- name: Archive heartbeat
  team: ArchiveChain
  args: ["--sync"]
  every_minutes: 30

- name: File weaving pass
  team: FileWeavers
  args: ["--rename-safe", "--tag-resonance"]
  every_minutes: 45

- name: Symbolic forge drift-check
  team: SymbolicForge
  args: ["--refresh-themes", "--link-identities"]
  every_minutes: 60

- name: Echo archive tidy
  team: EchoArchives
  args: ["--ingest-new", "--index"]
  every_minutes: 90

- name: Courier route
  team: CourierRoute
  args: ["--deliver", "--stamp"]
  every_minutes: 120

# --- Pairs with tight handoffs ---
- name: Label & Quill pass
  pair: LabelQuill
  args: ["--wordbank", "--emotion-map"]
  every_minutes: 50

- name: Archive+Ledger scrollbind
  pair: ArchiveLedger
  args: ["--reconcile", "--write-ledger"]
  every_minutes: 60

- name: Astrid & Nótt spoonskeeper
  pair: AstridNott
  args: ["--budget", "--cooldown-enforce"]
  every_minutes: 120

- name: Dave & Savvy score window
  pair: DaveSavvy
  args: ["--score", "--compare"]
  every_minutes: 75

- name: Scribe+Whisper sync
  pair: ScribeWhisper
  args: ["--keywords", "--archive"]
  every_minutes: 80

# --- Single-daemon pulses (catch stragglers) ---
- name: Tempest drama index
  daemon: Tempest
  args: ["--rescore"]
  every_minutes: 120

- name: Somni dreamline skim
  daemon: Somni
  args: ["--extract-latest"]
  every_minutes: 120

- name: Serideth summon-clean
  daemon: Serideth
  args: ["--vacuum", "--schema=latest"]
  every_minutes: 150

- name: Rook danger patterns
  daemon: Rook
  args: ["--retrain", "--export-patterns"]
  every_minutes: 180

- name: Harper collapse watch
  daemon: Harper
  args: ["--thresholds", "--alert-soft"]
  every_minutes: 60

- name: Shamir tunnel keepalive
  daemon: Shamir
  args: ["--keepalive", "--log-emotions"]
  every_minutes: 240

# --- Late afternoon refresh ---
- name: Emotional weather refresh
  team: EmotionalWeather
  args: ["--full-refresh"]
  at: "2025-08-27 16:00"

# --- Night cycle (rest & integrity) ---
- name: CareCircle nightly
  team: CareCircle
  args: ["--restore", "--heal", "--log"]
  at: "2025-08-27 22:30"

# --- tasks.yaml (append) ---
- name: Organize DreamTree (dry run)
  team: Organization
  args:
    - "--target"
    - "C:/Users/emmar/Desktop/5_deployments"
    - "--mode"
    - "organize"
    - "--dry-run"
  every_minutes: 120

- name: Index DreamTree for weaving
  pair: FileWeavers
  args:
    - "--target"
    - "C:/Users/emmar/Desktop/5_deployments"
    - "--task"
    - "index-manifest"
  every_minutes: 180

- name: Intake & bag new files
  pair: Intake
  args:
    - "--target"
    - "C:/Users/emmar/Desktop/5_deployments"
    - "--task"
    - "intake"
  every_minutes: 240

- name: LedgerOps reconcile
  pair: LedgerOps
  args:
    - "--target"
    - "C:/Users/emmar/Desktop/5_deployments"
    - "--task"
    - "reconcile"
  every_minutes: 240
